[package]
name = "zach-ai"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["openai", "anthropic", "rustls-tls"]
openai = []
anthropic = []
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dependencies]
zach-ai-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
futures.workspace = true
reqwest = { workspace = true, features = ["json", "stream"] }
tracing.workspace = true
